name: shope
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  card_swiper: ^3.0.1
  rubber: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0
  pin_code_text_field: ^1.8.0
  http: ^1.2.2
  flutter_rating_bar: ^4.0.1
  intl: ^0.20.1
  numberpicker: ^2.1.2
  flutter_svg: ^2.0.16
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  flutter_launcher_icons: ^0.14.2
  json_serializable: ^6.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/shopeLogo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/


  fonts:
  - family: Montserrat
    fonts:
    - asset: fonts/Montserrat-Regular.ttf
  - family: NunitoSans
    fonts:
    - asset: fonts/NunitoSans-Regular.ttf

